import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/Navbar";
import AppContextProvider from "@/context/AppContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ToastProvider } from "@/lib/ToastProvider";
import Loading from "@/components/ui/Loading";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string}>

        <AppContextProvider>
        <Navbar/>
        {children}
        <ToastProvider/>
        <Loading/>
        </AppContextProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
